### ISSUE TITLE
Limit max number of threads

### ISSUE THREAD

**Issue by fredericojordan** [marcelosalles/outputs-rtq-c#2]
On this line https://github.com/marcelosalles/outputs-rtq-c/blob/83a7226d70a0056d96b28e922e0f05e06b8f888e/outputs_01-23_Todos.py#L186 we are triggering a thread for each eligible folder. If the folder count is too high, I suppose we'll be losing more time switching contexts than actually processing anything. I suggest we limit this number to a reasonable maximum.

**Comment by marcelosalles** [comment]
It has been fixed to the maximum of 8 threads.
