### ISSUE TITLE
Use a single language throughout the code

### ISSUE THREAD

**Issue by fredericojordan** [marcelosalles/outputs-rtq-c#4]
Right now, the outputs we're giving are using a mixture of languages, as seen on these lines:
https://github.com/marcelosalles/outputs-rtq-c/blob/de2f62ba98e433ca6732d3ba5367b46c0b060f75/main.py#L180
https://github.com/marcelosalles/outputs-rtq-c/blob/de2f62ba98e433ca6732d3ba5367b46c0b060f75/main.py#L197

Shouldn't we make it so that everything in our code is either all in english or all in portuguese? The same thing goes for variable and function naming, not only output messages.

**Comment by marcelosalles** [comment]
I agree. Let's make it all in english, so later when we have an interface, we can translate only what the user sees to whatever language.
