### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by fredericojordan** [marcelosalles/outputs-rtq-c#5]
We should change the repository's name to `outputs-rtq-r`.

**Comment by fredericojordan** [comment]
To be honest, this name can be improved a bit more.
Maybe call it `rtq-r-parser` or something like that?
@marcelosalles, what do you think?

**Comment by fredericojordan** [comment]
Maybe `rqt-r-manager`?
@marcelosalles

**Comment by marcelosalles** [comment]
RTQ is what we are using it for, but it has nothing to do with what the code does
